import { supabase } from '../lib/supabase'

export type ReportType = 'hiring_summary' | 'pipeline_analysis' | 'time_to_hire' | 'source_effectiveness' | 'onboarding_progress'

interface DateRange {
  start: string
  end: string
}

interface ReportSection {
  title: string
  content: string
}

function buildHTML(title: string, sections: ReportSection[], dateRange: DateRange): string {
  const dateFrom = new Date(dateRange.start).toLocaleDateString()
  const dateTo = new Date(dateRange.end).toLocaleDateString()
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #1e293b; }
  h1 { font-size: 24px; border-bottom: 2px solid #003d9a; padding-bottom: 8px; }
  h2 { font-size: 18px; color: #003d9a; margin-top: 24px; }
  .meta { color: #64748b; font-size: 14px; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  th { background: #f1f5f9; font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
  .kpi { display: inline-block; background: #f1f5f9; border-radius: 8px; padding: 12px 16px; margin: 4px; min-width: 140px; }
  .kpi .value { font-size: 28px; font-weight: 700; color: #003d9a; }
  .kpi .label { font-size: 12px; color: #64748b; margin-top: 4px; }
  .bar { height: 16px; background: #e2e8f0; border-radius: 4px; overflow: hidden; margin: 4px 0; }
  .bar-fill { height: 100%; background: #003d9a; border-radius: 4px; }
  .section { margin-bottom: 24px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="meta">Report period: ${dateFrom} – ${dateTo} | Generated: ${new Date().toLocaleString()}</p>
${sections.map(s => `<div class="section"><h2>${s.title}</h2>${s.content}</div>`).join('\n')}
<div class="footer">Generated by AdminMate AI</div>
</body>
</html>`
}

function kpiBox(value: string, label: string): string {
  return `<div class="kpi"><div class="value">${value}</div><div class="label">${label}</div></div>`
}

function barRow(label: string, value: number, max: number, color = '#003d9a'): string {
  const pct = max > 0 ? Math.round((value / max) * 100) : 0
  return `<tr><td>${label}</td><td style="width:60%"><div class="bar"><div class="bar-fill" style="width:${pct}%;background:${color}"></div></div></td><td style="text-align:right;font-weight:600">${value}</td></tr>`
}

export async function generateHiringSummary(companyId: string, dateRange: DateRange): Promise<{ html: string; title: string }> {
  const [appsRes, hiredRes, jobsRes] = await Promise.all([
    supabase.from('applications').select('id, status, created_at', { count: 'exact' }).eq('company_id', companyId).gte('created_at', dateRange.start).lte('created_at', dateRange.end),
    supabase.from('applications').select('id, created_at, updated_at').eq('company_id', companyId).eq('status', 'hired').gte('created_at', dateRange.start).lte('created_at', dateRange.end),
    supabase.from('jobs').select('id, title, status').eq('company_id', companyId),
  ])

  const totalApps = appsRes.count || 0
  const hired = hiredRes.data || []
  const hiredCount = hired.length
  const activeJobs = (jobsRes.data || []).filter(j => j.status === 'open').length
  const conversionRate = totalApps > 0 ? Math.round((hiredCount / totalApps) * 100) : 0

  const statusCounts = (appsRes.data || []).reduce((acc: Record<string, number>, a: { status: string }) => {
    acc[a.status] = (acc[a.status] || 0) + 1
    return acc
  }, {} as Record<string, number>)

  const sections: ReportSection[] = [
    {
      title: 'Key Metrics',
      content: `<div>${kpiBox(String(totalApps), 'Total Applications')}${kpiBox(String(hiredCount), 'Hired')}${kpiBox(String(activeJobs), 'Open Positions')}${kpiBox(`${conversionRate}%`, 'Conversion Rate')}</div>`,
    },
    {
      title: 'Applications by Status',
      content: `<table><thead><tr><th>Status</th><th>Count</th><th style="text-align:right">%</th></tr></thead><tbody>${
        Object.entries(statusCounts).map(([status, count]) =>
          `<tr><td>${status.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}</td><td>${count}</td><td style="text-align:right">${totalApps > 0 ? Math.round((count / totalApps) * 100) : 0}%</td></tr>`
        ).join('')
      }</tbody></table>`,
    },
  ]

  const title = `Hiring Summary Report`
  return { html: buildHTML(title, sections, dateRange), title }
}

export async function generatePipelineAnalysis(companyId: string, dateRange: DateRange): Promise<{ html: string; title: string }> {
  const { data } = await supabase.rpc('get_pipeline_counts', { p_company_id: companyId })
  const pipeline = (data || {}) as Record<string, number>

  const stages = [
    { id: 'applied', label: 'Applied' },
    { id: 'ai_screening', label: 'AI Screening' },
    { id: 'shortlisted', label: 'Shortlisted' },
    { id: 'interviewing', label: 'Interviewing' },
    { id: 'offered', label: 'Offered' },
    { id: 'hired', label: 'Hired' },
    { id: 'rejected', label: 'Rejected' },
  ]

  const maxVal = Math.max(...Object.values(pipeline).map(Number), 1)

  const sections: ReportSection[] = [
    {
      title: 'Pipeline Funnel',
      content: `<table><thead><tr><th>Stage</th><th style="width:60%">Volume</th><th style="text-align:right">Count</th></tr></thead><tbody>${
        stages.map(s => barRow(s.label, pipeline[s.id] || 0, maxVal)).join('')
      }</tbody></table>`,
    },
  ]

  const total = stages.reduce((sum, s) => sum + (pipeline[s.id] || 0), 0)
  const hiredPct = total > 0 ? Math.round(((pipeline.hired || 0) / total) * 100) : 0
  const rejectPct = total > 0 ? Math.round(((pipeline.rejected || 0) / total) * 100) : 0

  sections.push({
    title: 'Conversion Summary',
    content: `<div>${kpiBox(`${hiredPct}%`, 'Hired of Total')}${kpiBox(`${rejectPct}%`, 'Rejected Rate')}${kpiBox(String(total), 'Total Candidates')}</div>`,
  })

  const title = `Pipeline Analysis Report`
  return { html: buildHTML(title, sections, dateRange), title }
}

export async function generateTimeToHire(companyId: string, dateRange: DateRange): Promise<{ html: string; title: string }> {
  const { data: hired } = await supabase
    .from('applications')
    .select('id, created_at, updated_at, candidates(full_name), jobs(title)')
    .eq('company_id', companyId)
    .eq('status', 'hired')
    .gte('created_at', dateRange.start)
    .lte('created_at', dateRange.end)

  const apps = (hired || []) as Array<{ created_at: string; updated_at: string; candidates?: { full_name?: string }; jobs?: { title?: string } }>
  const daysList = apps.map(a => {
    const ms = new Date(a.updated_at).getTime() - new Date(a.created_at).getTime()
    return Math.round(ms / (1000 * 60 * 60 * 24))
  })

  const avgDays = daysList.length > 0 ? Math.round(daysList.reduce((s, d) => s + d, 0) / daysList.length) : 0
  const minDays = daysList.length > 0 ? Math.min(...daysList) : 0
  const maxDays = daysList.length > 0 ? Math.max(...daysList) : 0
  const median = daysList.length > 0 ? daysList.sort((a, b) => a - b)[Math.floor(daysList.length / 2)] : 0

  const sections: ReportSection[] = [
    {
      title: 'Time-to-Hire Metrics',
      content: `<div>${kpiBox(`${avgDays}d`, 'Average')}${kpiBox(`${median}d`, 'Median')}${kpiBox(`${minDays}d`, 'Fastest')}${kpiBox(`${maxDays}d`, 'Slowest')}</div>`,
    },
    {
      title: 'Individual Hires',
      content: apps.length > 0
        ? `<table><thead><tr><th>Candidate</th><th>Position</th><th>Days to Hire</th></tr></thead><tbody>${
            apps.map(a => `<tr><td>${a.candidates?.full_name || 'N/A'}</td><td>${a.jobs?.title || 'N/A'}</td><td>${Math.round((new Date(a.updated_at).getTime() - new Date(a.created_at).getTime()) / (1000 * 60 * 60 * 24))} days</td></tr>`).join('')
          }</tbody></table>`
        : '<p>No hires in this period.</p>',
    },
  ]

  const title = `Time-to-Hire Report`
  return { html: buildHTML(title, sections, dateRange), title }
}

export async function generateSourceEffectiveness(companyId: string, dateRange: DateRange): Promise<{ html: string; title: string }> {
  const { data: candidates } = await supabase
    .from('candidates')
    .select('id, source, created_at')
    .eq('company_id', companyId)
    .gte('created_at', dateRange.start)
    .lte('created_at', dateRange.end)

  const { data: hired } = await supabase
    .from('applications')
    .select('candidate_id, candidates(source)')
    .eq('company_id', companyId)
    .eq('status', 'hired')
    .gte('created_at', dateRange.start)
    .lte('created_at', dateRange.end)

  const allSources = (candidates || []) as Array<{ source?: string }>
  const hiredSources = (hired || []) as Array<{ candidates?: { source?: string } }>

  const sourceCounts: Record<string, number> = {}
  allSources.forEach(c => { const s = c.source || 'Other'; sourceCounts[s] = (sourceCounts[s] || 0) + 1 })

  const hiredBySource: Record<string, number> = {}
  hiredSources.forEach(h => { const s = h.candidates?.source || 'Other'; hiredBySource[s] = (hiredBySource[s] || 0) + 1 })

  const total = allSources.length || 1
  const maxCount = Math.max(...Object.values(sourceCounts), 1)

  const rows = Object.entries(sourceCounts)
    .sort(([, a], [, b]) => b - a)
    .map(([source, count]) => {
      const hiredCount = hiredBySource[source] || 0
      const convRate = count > 0 ? Math.round((hiredCount / count) * 100) : 0
      return { source, count, hiredCount, convRate }
    })

  const sections: ReportSection[] = [
    {
      title: 'Source Breakdown',
      content: `<table><thead><tr><th>Source</th><th style="width:40%">Volume</th><th style="text-align:right">Candidates</th><th style="text-align:right">Hired</th><th style="text-align:right">Conv.</th></tr></thead><tbody>${
        rows.map(r => `<tr><td>${r.source}</td><td><div class="bar"><div class="bar-fill" style="width:${Math.round((r.count / maxCount) * 100)}%"></div></div></td><td style="text-align:right">${r.count} (${Math.round((r.count / total) * 100)}%)</td><td style="text-align:right">${r.hiredCount}</td><td style="text-align:right;font-weight:600">${r.convRate}%</td></tr>`).join('')
      }</tbody></table>`,
    },
  ]

  const bestSource = rows.length > 0 ? rows.reduce((best, r) => r.convRate > best.convRate ? r : best) : null
  if (bestSource) {
    sections.push({
      title: 'Top Performing Source',
      content: `<div>${kpiBox(bestSource.source, 'Best Conversion')}${kpiBox(`${bestSource.convRate}%`, 'Conversion Rate')}${kpiBox(String(bestSource.count), 'Total Candidates')}</div>`,
    })
  }

  const title = `Source Effectiveness Report`
  return { html: buildHTML(title, sections, dateRange), title }
}

export async function generateOnboardingProgress(companyId: string, dateRange: DateRange): Promise<{ html: string; title: string }> {
  const { data: checklists } = await supabase
    .from('onboarding_checklists')
    .select('id, status, progress_percentage, created_at, user_profiles!employee_id(full_name)')
    .eq('company_id', companyId)
    .gte('created_at', dateRange.start)
    .lte('created_at', dateRange.end)

  const lists = (checklists || []) as Array<{ id: string; status: string; progress_percentage: number; user_profiles?: { full_name?: string } }>
  const total = lists.length
  const completed = lists.filter(l => l.status === 'completed').length
  const inProgress = lists.filter(l => l.status === 'in_progress').length
  const avgProgress = total > 0 ? Math.round(lists.reduce((s, l) => s + (l.progress_percentage || 0), 0) / total) : 0
  const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0

  const sections: ReportSection[] = [
    {
      title: 'Onboarding Metrics',
      content: `<div>${kpiBox(String(total), 'Total Checklists')}${kpiBox(`${completionRate}%`, 'Completion Rate')}${kpiBox(String(inProgress), 'In Progress')}${kpiBox(`${avgProgress}%`, 'Avg Progress')}</div>`,
    },
    {
      title: 'Individual Progress',
      content: total > 0
        ? `<table><thead><tr><th>Employee</th><th style="width:50%">Progress</th><th style="text-align:right">Status</th></tr></thead><tbody>${
            lists.map(l => `<tr><td>${l.user_profiles?.full_name || 'N/A'}</td><td><div class="bar"><div class="bar-fill" style="width:${l.progress_percentage || 0}%"></div></div><span style="font-size:12px;color:#64748b">${l.progress_percentage || 0}%</span></td><td style="text-align:right"><span style="padding:2px 8px;border-radius:4px;font-size:12px;background:${l.status === 'completed' ? '#dcfce7' : '#fef3c7'};color:${l.status === 'completed' ? '#166534' : '#92400e'}">${l.status}</span></td></tr>`).join('')
          }</tbody></table>`
        : '<p>No onboarding checklists in this period.</p>',
    },
  ]

  const title = `Onboarding Progress Report`
  return { html: buildHTML(title, sections, dateRange), title }
}

export const reportGenerators: Record<ReportType, (companyId: string, dateRange: DateRange) => Promise<{ html: string; title: string }>> = {
  hiring_summary: generateHiringSummary,
  pipeline_analysis: generatePipelineAnalysis,
  time_to_hire: generateTimeToHire,
  source_effectiveness: generateSourceEffectiveness,
  onboarding_progress: generateOnboardingProgress,
}
