CREATE TABLE companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    name_th VARCHAR(255),
    tax_id VARCHAR(50),
    industry VARCHAR(100),
    logo_url TEXT,
    website_url TEXT,
    address TEXT,
    city VARCHAR(100),
    country VARCHAR(10) DEFAULT 'TH',
    currency VARCHAR(3) DEFAULT 'THB',
    timezone VARCHAR(50) DEFAULT 'Asia/Bangkok',
    locale VARCHAR(10) DEFAULT 'th-TH',
    phone VARCHAR(50),
    email VARCHAR(255),
    settings JSONB DEFAULT '{}',
    subscription_tier VARCHAR(20) DEFAULT 'free',
    subscription_expires_at TIMESTAMPTZ,
    max_employees INTEGER DEFAULT 10,
    line_oa_channel_id VARCHAR(255),
    whatsapp_phone_number_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
