CREATE TABLE offers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    job_id UUID NOT NULL REFERENCES jobs(id),
    position_title VARCHAR(255) NOT NULL,
    salary_offered NUMERIC(12,2),
    salary_currency VARCHAR(3) DEFAULT 'THB',
    employment_type VARCHAR(50),
    start_date DATE,
    work_hours VARCHAR(50) DEFAULT '09:00-18:00',
    benefits TEXT[],
    special_conditions TEXT,
    offer_letter_pdf_url TEXT,
    offer_letter_content JSONB,
    status VARCHAR(20) DEFAULT 'draft',
    sent_at TIMESTAMPTZ,
    viewed_at TIMESTAMPTZ,
    responded_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    candidate_response TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
