CREATE TABLE applications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    cv_document_id UUID REFERENCES cv_documents(id),
    status VARCHAR(30) DEFAULT 'applied',
    ai_match_score NUMERIC(5,2),
    ai_analysis JSONB,
    ai_skill_match JSONB,
    ai_experience_match TEXT,
    ai_missing_skills TEXT[],
    ai_suggested_questions TEXT[],
    ai_summary TEXT,
    recruiter_notes TEXT,
    rejection_reason TEXT,
    applied_at TIMESTAMPTZ DEFAULT NOW(),
    screened_at TIMESTAMPTZ,
    shortlisted_at TIMESTAMPTZ,
    interviewed_at TIMESTAMPTZ,
    offered_at TIMESTAMPTZ,
    hired_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(job_id, candidate_id)
);
