CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    created_by UUID NOT NULL REFERENCES user_profiles(id),
    title VARCHAR(255) NOT NULL,
    title_th VARCHAR(255),
    department VARCHAR(100),
    location VARCHAR(255),
    employment_type VARCHAR(50) DEFAULT 'full_time',
    experience_level VARCHAR(50),
    salary_min NUMERIC(12,2),
    salary_max NUMERIC(12,2),
    salary_currency VARCHAR(3) DEFAULT 'THB',
    country_override VARCHAR(10),
    currency_override VARCHAR(3),
    description TEXT,
    description_th TEXT,
    responsibilities TEXT[],
    requirements TEXT[],
    nice_to_have TEXT[],
    skills_required TEXT[],
    status VARCHAR(20) DEFAULT 'draft',
    application_deadline DATE,
    headcount INTEGER DEFAULT 1,
    filled_count INTEGER DEFAULT 0,
    ai_generated BOOLEAN DEFAULT false,
    ai_prompt_used TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
