CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    candidate_id UUID REFERENCES candidates(id) ON DELETE SET NULL,
    employee_id UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
    offer_id UUID REFERENCES offers(id) ON DELETE SET NULL,
    document_type VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    name_th VARCHAR(255),
    description TEXT,
    file_url TEXT,
    template_id VARCHAR(50),
    template_data JSONB,
    status VARCHAR(20) DEFAULT 'draft',
    due_date DATE,
    region VARCHAR(10) NOT NULL,
    language VARCHAR(5) DEFAULT 'th',
    requires_signature BOOLEAN DEFAULT false,
    signed_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    reminder_enabled BOOLEAN DEFAULT true,
    last_reminder_at TIMESTAMPTZ,
    reminder_count INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
